[package]
name = "registrar-bot"
version = "0.1.0"
authors = ["lamafab <42901763+lamafab@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "lib"
path = "src/lib.rs"

[[bin]]
name = "registrar-bot"
path = "src/bin/main.rs"

[dependencies]
tokio = { version = "0.2.22", features = ["macros"] }
futures = "0.3.5"
async-trait = "0.1.40"
failure = "0.1.8"
serde = "1.0.116"
serde_json = "1.0.57"
crossbeam = "0.7.3"
websockets = "0.1.5"
reqwest = "0.10.8"
urlencoding = "1.1.1"
matrix-sdk = { version = "0.1.0", git = "https://github.com/matrix-org/matrix-rust-sdk.git" }
oauth2 = { version = "3.0", features = ["reqwest-010", "futures-03"], default-features = false }
jwt = { version = "0.10.0", features = ["openssl"] }
openssl = "0.10.30"
sha2 = "0.9.1"
base58 = "0.1.0"
url = "2.1.1"
rocksdb = "0.15.0"
schnorrkel = "0.9.1"
rand = "0.7.3"
hex = "0.4.2"
