[package]
name = "registrar-bot"
version = "0.1.2"
authors = ["lamafab <42901763+lamafab@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "registrar"
path = "src/lib.rs"

[[bin]]
name = "registrar-bot"
path = "src/bin/main.rs"

[dependencies]
log = { version = "0.4.11", features = ["serde"] }
env_logger = "0.7.1"
tokio = { version = "1.2.0", features = ["macros", "time", "process", "rt-multi-thread" ] }
tokio_02 = { version = "0.2", package = "tokio", features = ["macros", "time", "process"] }
futures = "0.3.5"
mongodb = "2.0.0-beta"
bson = "2.0.0-beta"
reqwest = "0.11.3"
urlencoding = "1.3.3"
parity-scale-codec = "1.0.0"
frame-system = "2.0.0"
sp-runtime = "2.0.0"
serde_yaml = "0.8.15"
async-trait = "0.1.40"
actix = { version = "0.11.1", features = ["macros"]}
actix-web = "4.0.0-beta.6"
actix-broker = "0.4.0"
actix-web-actors = { git = "https://github.com/actix/actix-web.git", tag = "web-v4.0.0-beta.6" } 
actix-test = { git = "https://github.com/actix/actix-web.git", tag = "web-v4.0.0-beta.6" } 
thiserror = "1.0.23"
anyhow = "1.0.38"
serde = "1.0.116"
serde_json = "1.0.57"
matrix-sdk = "0.2.0"
lettre = "0.9.0"
lettre_email = "0.9.4"
imap = "2.4.1"
mailparse = "0.13.0"
native-tls = "0.2.4"
hmac = "0.9.0"
sha-1 = "0.9.1"
sha2 = "0.9.1"
base64 = "0.12.3"
url = "2.1.1"
rand = "0.7.3"
hex = "0.4.2"
strsim = "0.10.0"

[dev-dependencies]
actix-http = "3.0.0-beta.6"
