[package]
name = "registrar-bot"
version = "0.1.0"
authors = ["lamafab <42901763+lamafab@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "registrar-bot"
path = "src/bin/main.rs"

[dependencies]
tokio = { version = "0.2.22", features = ["macros"] }
futures = "0.3.5"
async-trait = "0.1.40"
serde = "1.0.116"
serde_json = "1.0.57"
matrix-sdk = { version = "0.1.0", git = "https://github.com/matrix-org/matrix-rust-sdk.git" }
url = "2.1.1"
rocksdb = "0.15.0"
schnorrkel = "0.9.1"
rand = "0.7.3"
hex = "0.4.2"
