[package]
name = "registrar-bot"
version = "0.1.2"
authors = ["lamafab <42901763+lamafab@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "registrar"
path = "src/lib.rs"

[[bin]]
name = "registrar-bot"
path = "src/bin/main.rs"

[dependencies]
log = { version = "0.4.11", features = ["serde"] }
env_logger = "0.7.1"
tokio = { version = "1.2.0", features = ["macros", "time", "process", "rt-multi-thread" ] }
tokio_02 = { version = "0.2", package = "tokio", features = ["macros", "time", "process"] }
futures = "0.3.5"
eventstore = "0.9.9"
serde_yaml = "0.8.15"
eventually = { path = "../eventually-rs/eventually" }
eventually-event-store-db = { path = "../eventually-rs/eventually-event-store-db", features = ["verify-connection"] }
async-trait = "0.1.40"
jsonrpc-core = "17.0.0"
jsonrpc-derive = "17.0.0"
jsonrpc-ws-server = "17.0.0"
jsonrpc-pubsub = "17.0.0"
jsonrpc-core-client = "17.0.0"
jsonrpc-client-transports = "17.0.0"
async-channel = "1.5.1"
parking_lot = "0.11.1"
lock_api = "0.4.2"
thiserror = "1.0.23"
anyhow = "1.0.38"
reqwest = "0.11.0"
tungstenite = "0.11.1"
tokio-tungstenite = "0.11.0"
serde = "1.0.116"
serde_json = "1.0.57"
urlencoding = "1.1.1"
matrix-sdk = { version = "0.2.0", git = "https://github.com/matrix-org/matrix-rust-sdk.git" }
lettre = "0.9.0"
lettre_email = "0.9.4"
imap = { version = "2.4.1", path = "../rust-imap" }
mailparse = "0.13.0"
native-tls = "0.2.4"
hmac = "0.9.0"
sha-1 = "0.9.1"
sha2 = "0.9.1"
base64 = "0.12.3"
url = "2.1.1"
rand = "0.7.3"
hex = "0.4.2"
strsim = "0.10.0"
