version: 2

jobs:

  helmLint:
    docker:
      - image: web3f/ci-commons:v2.4.4
    steps:
      - checkout
      - run:
          command: |
            helm lint ./charts/polkadot-registrar-challenger

  buildImage:
    docker:
      - image: web3f/ci-commons:v2.4.4
    resource_class: xlarge  
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 19.03.13
      - run:
          command: |
            /scripts/build-image.sh web3f/polkadot-registrar-challenger .
            
  integrationTests:
    docker:
      - image: web3f/ci-commons:v2.4.4
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          description: run integration tests
          command: |
            /scripts/integration-tests.sh            

  publishImage:
    docker:
      - image: web3f/ci-commons:v2.4.4
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            /scripts/publish-image.sh web3f/polkadot-registrar-challenger

  publishChart:
    docker:
      - image: web3f/ci-commons:v2.4.4
    steps:
      - checkout
      - run:
          command: |
            /scripts/publish-chart.sh
  deploy:
      docker:
        - image: web3f/ci-commons:v2.4.4
      steps:
        - checkout
        - run:
            environment:
              GCP_REGION: europe-west3
              HELM_ENV: production
            command: |
              /scripts/deploy.sh -c engineering          

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - helmLint:
          filters:
            tags:
              only: /.*/
      - buildImage:
          context: dockerhub-bot
          filters:
            tags:
              only: /.*/
          requires:
            - helmLint 
      - integrationTests:
          filters:
            tags:
              only: /.*/
          requires:
            - buildImage        
      - publishImage:
          context: dockerhub-bot
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
          requires:
            - buildImage
            - integrationTests
      - publishChart:
          context: dockerhub-bot
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
          requires:
            - buildImage              
      - deploy:
          context: 
            - engineering-access-registrar
            - registrar-v2
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
          requires:
            - publishImage
            - publishChart      
