environment: production

image:
  repo: web3f/polkadot-registrar-challenger
  tag: v0.1.2

config:
  port: 3000
  registrar_db_path: "/app/registrar.db"
  matrix_db_path: "/app/matrix.db"
  log_level: "DEBUG"
  watcher_url: "ws://localhost:3001"
  enable_watcher: true
  matrix_homeserver: "https://matrix-client.matrix.org"
  matrix_username: "test-account-15883"
  matrix_password: "9ZrQ8iMTqZ" 
   
resources: 
  requests:
    cpu: "300m"
    memory: "500Mi"
  limits:
    cpu: "500m"
    memory: "700Mi" 
