environment: production

image:
  repo: web3f/polkadot-registrar-challenger
  tag: v0.1.0

config:
  port: 3000  

resources: 
  requests:
    cpu: "300m"
    memory: "500Mi"
  limits:
    cpu: "500m"
    memory: "700Mi" 
