environments:
  production:
  ci:
  local:  

repositories:
- name: w3f
  url: https://w3f.github.io/helm-charts/
  
releases:

{{- if or (eq .Environment.Name "ci") (eq .Environment.Name "local") }} 
- name: registrar-watcher
  chart: w3f/polkadot-registrar-watcher
  values:
  - ./config/integration-test/registrar-watcher-values.yaml.gotmpl

- name: registrar-challenger
  chart: ../charts/polkadot-registrar-challenger
  values:
  - ./config/registrar-challenger-values.yaml.gotmpl
  - ./config/integration-test/registrar-challenger-values.yaml.gotmpl
{{- end }}

{{- if eq .Environment.Name "production" }}  
- name: registrar-challenger-adapter-listener
  namespace: registrar-v2
  chart: w3f/polkadot-registrar-challenger
  values:
  - ./config/registrar-challenger-values.adapter_listener.yaml.gotmpl

- name: registrar-challenger-session-notifier
  namespace: registrar-v2
  chart: w3f/polkadot-registrar-challenger
  values:
  - ./config/registrar-challenger-values.session_notifier.yaml.gotmpl
{{- end }}