environments:
  production:

repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
- name: nginx
  namespace: registrar-v2
  chart: bitnami/nginx
  version: 9.4.1
  values:
    - ./config/nginx.yaml.gotmpl
