{{ if (.Values.useDomain | default false) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/limit-rps: "10"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
      - registrar-backend.{{ .Values.domain }}
    secretName: registrar-backend-tls
  rules:
  - host: registrar-backend.{{ .Values.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: {{ .Values.backendPort }}
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: {{ .Values.backendPort }}
{{ end }}
