apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-pod-restarter
rules:
- apiGroups: ["apps"]
  verbs:
  - "get"
  resources:
  - "statefulsets"
- apiGroups: ["apps"]
  verbs:
  - "get"
  - "patch"
  resources:
  - "statefulsets/scale"